import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="min-h-screen bg-zinc-950 text-zinc-100">
          <nav className="border-b border-white/10 bg-zinc-950/60 backdrop-blur">
            <div className="mx-auto max-w-5xl px-4 py-4 flex items-center justify-between">
              <a href="/dashboard" className="font-bold tracking-tight text-lg">
                LibraTrack
              </a>

              <div className="flex gap-4 text-sm font-medium text-zinc-300">
                <a className="hover:text-white" href="/dashboard">Dashboard</a>
                <a className="hover:text-white" href="/books">Books</a>
                <a className="hover:text-white" href="/members">Members</a>
                <a className="hover:text-white" href="/borrow">Borrow</a>
                <a className="hover:text-white" href="/returns">Returns</a>
              </div>
            </div>
          </nav>

          <main className="mx-auto max-w-5xl px-4 py-8">{children}</main>
        </div>
      </body>
    </html>
  );

  

 
}
